### PR TITLE
fix(deps): update dependencies & Node 16 supports

### LINKED ISSUE #16: Dependency update to resolve npm audit issues
Hello,

This project is causing npm audit to fail for my builds, I was hoping it is ok if I submit a pr to resolve the audit issues.

` === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ trim-newlines                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.1 <4.0.0 || >=4.0.1                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ can-npm-publish [dev]                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ can-npm-publish > meow > trim-newlines                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1753                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
`

### PR DESCRIPTION
**Pull request by azu**
fix #16 
fix #17

### CODE REVIEW

File: lib/can-npm-publish.js [hunk 1]
```diff
@@ -56,15 +72,18 @@ const viewPackage = (packageName, registry) => {
...
         });
 
-        view.stderr.on("data", err => {
+        view.stderr.on("data", (err) => {
             errorResult += err.toString();
         });
 
-        view.on("close", code => {
+        view.on("close", (code) => {
+            if (code !== 0) {
```
Comment (azu) [inline lib/can-npm-publish.js:84]: Node.js 16 support.

When package is 404, `errorResult` is "" in Node.js 16.

File: test/fixtures/legacy-name.json [hunk 2]
```diff
@@ -1,5 +1,5 @@
 {
   "private": false,
-  "name": "lEgAcY-nAmE",
+  "name": "JSONStream",
```
Comment (azu) [inline test/fixtures/legacy-name.json:3]: use actual example
