### PR TITLE
fix: improve 404 logics

### LINKED ISSUE #19: 404 logic change
It seems like https://github.com/azu/can-npm-publish/commit/7967d92 changed the way 404s are treated.

For node 12 and 1.3.4 the exist code is 1 and `npm ERR! code E404` is printed to the terminal
For node 14 and 1.3.4 the exist code is 1 and `npm ERR! code E404` is printed to the terminal
For node 16 and 1.3.4 the exist code is 1 and `npm ERR! code E404` is printed to the terminal

For node 12 and 1.3.3 things are all good
For node 14 and 1.3.3 things are all good
For node 16 and 1.3.3 `can-npm-publish/lib/can-npm-publish.js:68:37` throws an `Unexpected end of JSON input`/`undefined` error

### PR DESCRIPTION
**Pull request by azu**
- npm(7.18.1) `--json` output include non JSON string.
- npm(7.18.1) `--json` output JSON string into stderr
- npm(6.x) `--json` output JSON string into stdout

For the reason, We need to parse stdout and stderr.

fix #19

### CODE REVIEW

File: lib/can-npm-publish.js [hunk 1]
```diff
@@ -69,32 +69,82 @@ const viewPackage = (packageName, registry) => {
...
-            errorResult += err.toString();
+            const stdErrorStr = err.toString();
+            try {
+                // Workaround for npm 7
+                // npm 7 --json option is broken
+                // It aim to remove non json output.
+                // FIXME: However,This logics will break json chunk(chunk may be invalid json)
+                // https://github.com/azu/can-npm-publish/issues/19
+                // https://github.com/npm/cli/issues/2740
+                JSON.parse(stdErrorStr); // parse check
```
Comment (azu) [inline lib/can-npm-publish.js]: npm 7 workaround

- [[BUG] npm view --json sompackage dist-tags has invalid json · Issue #3075 · npm/cli](https://github.com/npm/cli/issues/3075)
- [[BUG] npm view --json outputs illegal JSON for existing package but non-existent version · Issue #3184 · npm/cli](https://github.com/npm/cli/issues/3184)
- [[BUG] NPM 7.x broke the "--json" CLI parameter · Issue #2740 · npm/cli](https://github.com/npm/cli/issues/2740)

Comment (azu) [reply lib/can-npm-publish.js]: npm 7 outputs
```
"npm"
"Err!"
""
"JSON strings..."
""
```
...

Comment (azu) [reply lib/can-npm-publish.js]: This logic will break following pattern

```
"npm"
"Err!"
""
"JSON part1"
"JSON part2"
""
```

Comment (azu) [reply lib/can-npm-publish.js]: use https://github.com/bconnorwhite/extract-first-json for the error
https://github.com/azu/can-npm-publish/runs/2900472385
